Mutex file:${APACHE_LOCK_DIR} default
PidFile ${APACHE_PID_FILE}
Timeout 300
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}
HostnameLookups Off
ErrorLog /dev/stderr
LogLevel warn
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf
Listen 8080
 
<Directory />
    Options FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>
<Directory /usr/share>
    AllowOverride None
    Require all granted
</Directory>
<Directory /var/www/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

# FCGI
AddHandler         fcgid-script .fcgi
FcgidMaxRequestLen 104857600
FcgidIOTimeout     600

AliasMatch ^/kivitendo-erp/[^/]+\.pl$ /var/www/kivitendo-erp/fcgi/dispatcher.fcgi
Alias       /kivitendo-erp/webdav     /var/www/kivitendo-erp/webdav
Alias       /kivitendo-erp            /var/www/kivitendo-erp/public

<Directory "/var/www/kivitendo-erp/fcgi">
 Options +ExecCGI
 Require all granted
</Directory>

<Directory "/var/www/kivitendo-erp/public">
 Options -ExecCGI +FollowSymlinks
 Require all granted
</Directory>
 
AccessFileName .htaccess
 
<FilesMatch "^\.ht">
    Require all denied
</FilesMatch>
 
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent
 
IncludeOptional conf-enabled/*.conf
IncludeOptional sites-enabled/*
